import type { NextPage } from 'next'
import Head from 'next/head'
import { Home } from './Home'

const App: NextPage = () => (
  <div>
    <Head>
      <title>Feeds</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Home />
    </main>
  </div>
)

export default App
